language: node_js
before_install: npm install npm -g
node_js:
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
branches:
  only:
    - master
notifications:
  email:
    - r@va.gg
    - john@chesl.es
    - raynos2@gmail.com
    - dominic.tarr@gmail.com
    - max@maxogden.com
    - ralphtheninja@riseup.net
    - david.bjorklund@gmail.com
    - julian@juliangruber.com
    - paolo@async.ly
    - anton.whalley@nearform.com
    - matteo.collina@gmail.com
    - pedro.teixeira@gmail.com
    - mail@substack.net
script: npm test
